### ISSUE TITLE
bug with moving comma at the end of a line

### ISSUE THREAD

**Issue by oakmac** [oakmac/standard-clojure-style-js#104]
Follow-up from [Issue #102](https://github.com/oakmac/standard-clojure-style-js/issues/102)

[This is incorrect behavior.](https://github.com/scicloj/wolframite/pull/134/files#diff-446acbaf9922a80129a6c74a0f7c2af682a25b70b9137295c1474a084da04654R143) The comma at the end of the line should not be moved.

**Comment by oakmac** [comment]
The current behavior is clearly buggy, but I wonder if Standard Clojure Style should remove commas at the end of lines entirely? Not sure of a case where it makes a lot of sense to keep a comma at the end of a line.

**Comment by oakmac** [comment]
> I wonder if Standard Clojure Style should remove commas at the end of lines entirely?

![trailing-whitespace](https://github.com/user-attachments/assets/4c6e1427-dafd-47a2-8a44-9235d0fe41ef)

**Comment by oakmac** [comment]
I am leaning toward "Standard Clojure Style should treat eol commas as whitespace and remove them"

**Comment by NoahTheDuke** [comment]
Yes, and imo this aligns with the Clojure Style Guide. The "Optional Commas in Maps" section has a map with each entry on separate lines and no commas, and a map with both entries on one line and a comma between. Regardless of thoughts on the latter, the former indicates that commas shouldn't be at the end of the line.

**Comment by oakmac** [comment]
Fixed with [PR-107](https://github.com/oakmac/standard-clojure-style-js/pull/107)
