### ISSUE TITLE
Anonymous functions using #() are indented one space too little

### ISSUE THREAD

**Issue by axelarge** [oakmac/standard-clojure-style-js#108]
Maybe this intended behavior and part of a rule that I've missed, but I would expect the body of anon functions using reader syntax to be indented relative to the opening parenthesis, not the `#`.

That is, I would expect these to be formatted like
```clojure
(when :foo
  :bar)

#(when :foo
   :bar)
```

but instead the result is: 

```clojure
(when :foo
  :bar)

#(when :foo
  :bar)
```

![CleanShot 2024-10-09 at 12 26 48@2x](https://github.com/user-attachments/assets/77b5115f-90be-49b1-9ba3-3c1399e9b6e6)

**Comment by oakmac** [comment]
Fixed with [PR-116](https://github.com/oakmac/standard-clojure-style-js/pull/116)
