### ISSUE TITLE
Reader tagged literals result in incorrect alignment

### ISSUE THREAD

**Issue by axelarge** [oakmac/standard-clojure-style-js#110]
Please see screenshot:

![CleanShot 2024-10-09 at 12 59 44@2x](https://github.com/user-attachments/assets/457892b6-fde1-4870-a2a4-39908620f21d)

Input:
```clojure
(-> #js [(one-promise)
         (another-promise)]
    (js/Promise.all)
    (.then (fn [_])))

(-> #uuid "15adfdf0-2e6b-410e-a489-f71d1dd17642"
    str)
```

I would expect the code to be unchanged after formatting, but everything gets aligned to one character after `#`

```clojure
(-> #js [(one-promise)
         (another-promise)]
     (js/Promise.all)
     (.then (fn [_])))

(-> #uuid "15adfdf0-2e6b-410e-a489-f71d1dd17642"
     str)
```

I would guess that this is also what's causing #108.

**Comment by oakmac** [comment]
Fixed with [PR-118](https://github.com/oakmac/standard-clojure-style-js/pull/118)
