### ISSUE TITLE
ns declaration rewrite loses forms before `:require-macros`

### ISSUE THREAD

**Issue by axelarge** [oakmac/standard-clojure-style-js#111]
When rewriting a namespace declaration, any content before `:require-macros` is lost.
It doesn't seem to matter if the `:require-macros` gets moved or not.
![CleanShot 2024-10-09 at 13 16 02@2x](https://github.com/user-attachments/assets/c4041a8d-f6dd-489c-ad2e-6d2f20817acc)
![CleanShot 2024-10-09 at 13 18 49@2x](https://github.com/user-attachments/assets/89c77520-c9e4-47ce-900d-ef41a5eaaa7c)

**Comment by oakmac** [comment]
Thank you for the report! Fixed with [PR-115](https://github.com/oakmac/standard-clojure-style-js/pull/115)
