### ISSUE TITLE
Reader conditionals in NS declaration can break `:refer-clojure` forms

### ISSUE THREAD

**Issue by axelarge** [oakmac/standard-clojure-style-js#114]
![CleanShot 2024-10-09 at 14 17 42@2x](https://github.com/user-attachments/assets/502880a0-39b3-4af1-a5b2-cefab47503d3)

**Comment by oakmac** [comment]
Fixed with [PR-119](https://github.com/oakmac/standard-clojure-style-js/pull/119)
