### ISSUE TITLE
Alignment problem when using namespace map literals

### ISSUE THREAD

**Issue by svdo** [oakmac/standard-clojure-style-js#161]
Hi! Thanks for this tool, I appreciate what you're trying to accomplish with it! 

To test it, I just ran it on our code and one thing in particular is not quite right I believe. The easiest way to understand what I mean is by looking at the screenshot:

<img width="1160" alt="Screenshot 2024-11-20 at 13 27 18" src="https://github.com/user-attachments/assets/2d1dd69c-3fc5-4c55-9e7d-6956f3a6d095">

There are two things going on:

1. The indentation is (incorrectly) decreased with one space after every map in the list, and
2. I feel like the original alignment should be preserved.

I guess (2) is subjective but of course I feel very strongly about it 😉

**Comment by oakmac** [comment]
Thank you for the report! This looks like a bug to me.
