### ISSUE TITLE
Formatting breaks the `:require` block!

### ISSUE THREAD

**Issue by licht1stein** [oakmac/standard-clojure-style-js#166]
This is a very serious issue for us, standard-clj doesn't seem to be handling the `:rename` form correctly.

It turns:

```clojure
(ns hello
  (:require [other :refer :all :rename {foo bar}]))
```
into this:

``` clojure
(ns hello
  (:require
   [other :refer [bar foo]]))
```

Literally breaking the import and rendering the namespace unusable.

**Comment by oakmac** [comment]
Thank you for the report! Fixed with [PR-167](https://github.com/oakmac/standard-clojure-style-js/pull/167)

**Comment by oakmac** [comment]
This fix is available with v0.17.0. Can you confirm that it works for your codebase @licht1stein ?

**Comment by licht1stein** [comment]
Will check as soon as I have a chance, thanks for the quick fix!

**Comment by licht1stein** [comment]
Seems to be find with version 0.18.0, thank you!
