### ISSUE TITLE
idea: allow for single lines in the ns form

### ISSUE THREAD

**Issue by oakmac** [oakmac/standard-clojure-style-js#37]
We should allow for single line expressions in the `ns` form if they are sufficiently short.

I need to come up with some examples here, but I think this may result in cleaner `ns` forms in some cases.

**Comment by imrekoszo** [comment]
Not sure what you're referring to here, but if it's this:

```clj
(ns my.company.core
  (:require [clojure.string :as str]))
```

then consider that adding a second require to the above would result in a 3-line diff as opposed to a 1 or 2-line if the starting point was:

```clj
(ns my.company.core
  (:require
   [clojure.string :as str]))
```

**Comment by oakmac** [comment]
Closing this for now. [Issue #88](https://github.com/oakmac/standard-clojure-style-js/issues/88) has some related discussion.
