### ISSUE TITLE
rule 3 for nested forms?

### ISSUE THREAD

**Issue by oakmac** [oakmac/standard-clojure-style-js#56]
How should this be formatted?

```clj
(foo (bar biz
       baz)
     zzz)
```

### Option A

- `zzz` is not considered "Rule 3"
- format using fixed indentation

```clj
(foo (bar biz
       baz)
  zzz)
```

### Option B

- `zzz` is considered to be "Rule 3"

```clj
(foo (bar biz
       baz)
     zzz)
```

**Comment by oakmac** [comment]
I am leaning toward **Option B** as being what we want here.

**Comment by oakmac** [comment]
Fixed with [PR-57](https://github.com/oakmac/standard-clojure-style-js/pull/57)

**Comment by shaunlebron** [comment]
Agreed
