### ISSUE TITLE
ensure space before end of line comments?

### ISSUE THREAD

**Issue by oakmac** [oakmac/standard-clojure-style-js#62]
Should we always ensure a space before an end-of-line comment?

ie:

```clj
(aaa);;bbb
```

Becomes:

```clj
(aaa) ;;bbb
```

**Comment by oakmac** [comment]
I am leaning towards "yes, ensure at least one space".

I can imagine code where there might be multiple spaces before an eol comment in order to vertically align some comments / documentation.

But I cannot think of a context in which having no space improves readability?

**Comment by oakmac** [comment]
I also think it makes sense to ensure a space after the `;;`, so:

```clj
(aaa);;bbb
```

becomes:

```clj
(aaa) ;; bbb
```

**Comment by oakmac** [comment]
Fixed with [PR-85](https://github.com/oakmac/standard-clojure-style-js/pull/85)

**Comment by imrekoszo** [comment]
> ```clojure
> (let [ ;; which squares are the same in both positions?
> ```
> 
> Maybe we should only add the space after a closing paren or a non-opener token?

Why is this a problem though?

**Comment by oakmac** [comment]
> I think the rule might be as simple as "add at least one space before a ; comment if there is not one, unless the comment is immediately preceded by an opening paren (ie: (, [, {, etc)"

Added with [PR-90](https://github.com/oakmac/standard-clojure-style-js/pull/90)
