### ISSUE TITLE
Clarification:  Leading and trailing commas are removed?

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/standard-clojure-style-js#73]
Edit: When I saw this I was confused at why commas were being removed, but now I see that it’s a good idea to remove trailing commas because newlines are good enough separators for key-value pairs which the commas are mostly (only?) used for.

I also saw in our code that commas are used as ellipses `,,,` as placeholders.  One was on a line by itself holding a close-paren like `,,,)`.  I don’t think it should be supported, but we should be aware of it.

**Comment by oakmac** [comment]
* end-of-line commas get removed as if they are whitespace ([Issue #104](https://github.com/oakmac/standard-clojure-style-js/issues/104))
* commas on the next line can "hold" parens to prevent slurping ([Issue #60](https://github.com/oakmac/standard-clojure-style-js/issues/60#issuecomment-2363758273))
