### ISSUE TITLE
Bug: comment forms deleted after ns

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/standard-clojure-style-js#75]
before:

```
(ns foo.bar
  (:require baz.core
            ))

(comment
  ;; foo
  )


(comment
  ;; bar
  )

(comment
  ;; baz
  )
```

after:

```
(ns foo.bar
  (:require
    [baz.core]))
```

**Comment by shaunlebron** [comment]
If you add a function before the comment, then the function is deleted and the subsequent comments are reformatted but preserved.

**Comment by oakmac** [comment]
Fixed with [PR-82](https://github.com/oakmac/standard-clojure-style-js/pull/82)
