### ISSUE TITLE
Support standard input in CLI

### ISSUE THREAD

**Issue by imrekoszo** [oakmac/standard-clojure-style-js#86]
Would be nice to be able to execute something like the following:

```sh
echo '(ns my.company.core (:require [clojure.string :as str]))' | standard-clj fix -
```

and receive the formatted contents on stdout.

(The suggested `-` argument in the command above tells `standard-clj` to read/write from/to standard in/out)

**Comment by oakmac** [comment]
Thank for the suggestion! Done with [PR-91](https://github.com/oakmac/standard-clojure-style-js/pull/91)
