### ISSUE TITLE
ns require indentation does not adhere to indentation rule 2

### ISSUE THREAD

**Issue by imrekoszo** [oakmac/standard-clojure-style-js#87]
```clj
(ns my.company.core (:require [clojure.string :as str]))
```

is currently (`@chrisoakman/standard-clojure-style@0.3.0`) formatted to

```clj
(ns my.company.core
  (:require
    [clojure.string :as str]))
```

as opposed to

```clj
(ns my.company.core
  (:require
   [clojure.string :as str]))
```

[Rule 2](https://tonsky.me/blog/clojurefmt/):
> Other multi-line lists, vectors, maps and sets are aligned with the first element (1 or 2 spaces)

Edit: applies to other clauses as well:

```clj
(ns com.example.my-application.server
  "Example application HTTP server and routing."
  (:refer-clojure :exclude [atom count deref distinct empty first])
  (:require-macros
    [cljs.pprint :as pp])
  (:require
    [clojure.core.async :as async :refer [<! <!! >! >!!]]
    [com.example.my-application.base]
    [com.example.my-application.server.sse :as server.sse]
    [io.pedestal.http :as http]
    [io.pedestal.http.sse :as http.sse]
    [ring.util.response :as response])
  (:import
    (java.nio.file Files LinkOption)
    (org.apache.commons.io FileUtils))
  (:gen-class
    :init ctor
    :constructors undefined))
```

**Comment by NoahTheDuke** [comment]
I would expect that lists starting with keywords (function application in most cases) are treated as symbols for the purpose of indentation.

**Comment by imrekoszo** [comment]
> I would expect that lists starting with keywords (function application in most cases) are treated as symbols for the purpose of indentation.

I don't have a very strong opinion about this, it's just that my understanding of @tonsky's rule 1 is that it's only about symbols.

**Comment by oakmac** [comment]
I can see this either way. I think I prefer the 2 space indentation as it creates a stronger indentation impression, especially with reader conditionals.

The good news is: as the `ns` form is always "printed from scratch" it will always be consistent regardless of the initial input format.

**Comment by imrekoszo** [comment]
@oakmac are you looking to apply that 2 space indentation to other lists-starting-with-a-keyword as well, i.e. treating keywords as symbols for this purpose as Noah suggests, or are you looking to only do 2 spaces for the ones in the ns form? My personal preference would be consistency between the two.

**Comment by tonsky** [comment]
My 2 cents:

- Original idea was to have all lists indented with 2 spaces and all vectors/maps with one
- Because parinfer would be confused with something like

```
  ((abc)
    def)
```

we had to make exception (1 space) for when first place is list/vector/map.

So now we have a situation:

- Lists with symbol on first place — definitely 2 spaces
- Lists with list/vector/map on first place — definitely 1 space

But the rest is up to intepretation.

One can make a case that then reader macro will look off:

```
#?(:clj ...
    :cljs ...)
```

Also lists when they are just lists:

```
'(1
   2
   3)
```

So it looks like any list with non-symbol in first place should be 1-space indented?

**Comment by oakmac** [comment]
[PR-130](https://github.com/oakmac/standard-clojure-style-js/pull/130) adjusts `ns` indentation to match closer with the dominant community style
